version: "3.8"

services:
#Contenaire MariaDB
  mariadb:
    image: mariadb:10.7
    restart: always
    container_name: mariadb-glpi
    hostname: mariadb-glpi
    ports: 
    - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=glpi
      - MARIADB_DATABASE=glpidb
      - MARIADB_USER=glpi_user
      - MARIADB_PASSWORD=glpi

#Contenaire GLPI
  glpi:
    image: diouxx/glpi
    restart: always
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
